#ifndef PORTFORWARD_CONST_H
#define PORTFORWARD_CONST_H

#define PORTFORWARD_EXEC_ORG_BIN "lcserver_org"
#define PORTFORWARD_EXEC_BIN "lcserver"
#define PORTFORWARD_CERT_DIR "./cer"

#define MAX_CONNECTIONS 10000
#define BUFFER_SIZE 8192
#define WS_PORT_OFFSET_WS 10000
#define WS_PORT_OFFSET_WSS 20000
#define MAX_EVENTS 1024


#endif // PORTFORWARD_CONST_H
